server.port = 8090
spring.application.name = CNPS Fund approval
spring.jmx.default-domain: CNPS

spring.batch.job.enabled=false

server.servlet.session.timeout=60m

# =============================== 
# = DATA SOURCE
# ===============================
# pre-production
spring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect
spring.jpa.hibernate.ddl-auto=none
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.validationQuery = SELECT 1
spring.jpa.hibernate.show-sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation= true

spring.datasource.url = jdbc:mysql://localhost:3306/cnps_fund_approval?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username= root
spring.datasource.password= Root@123
spring.datasource.testWhileIdle = true

spring.jpa.show-sql = true

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-timeout=30000


spring.thymeleaf.template-loader-path: classpath:/templates
spring.thymeleaf.suffix: .html
spring.thymeleaf.cache: false

spring.messages.basename=validation

# RabbitMQ
#spring.rabbitmq.host=localhost
#spring.rabbitmq.virtualhost=CNPS_vhost
#spring.rabbitmq.port=5672
#spring.rabbitmq.username=bhadram
#spring.rabbitmq.password=Bhadram1#
#spring.rabbitmq.exchange=CNPS_topic_exchange
#spring.rabbitmq.queue=CNPS_FA_queue
#spring.rabbitmq.routingkey=CNPS_routing_key
#spring.rabbitmq.reply.timeout=60000
#spring.rabbitmq.concurrent.consumers=1
#spring.rabbitmq.max.concurrent.consumers=1

queue.name=CNPS_FA_queue

spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.properties.org.hibernate.envers.audit_table_suffix = _AUDIT
spring.jpa.properties.org.hibernate.envers.revision_field_name = REVISION_ID
spring.jpa.properties.org.hibernate.envers.revision_type_field_name= REVISION_TYPE

#logging.level.org.springframework = DEBUG
#logging.level.org.springframework.security = DEBUG


logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG


spring.weight.Maxweight=1000
spring.mobileno.length=10
spring.thirtytwo.length=32
spring.twenty.length=20


# ===============================
# = SMS GATWAY CHANNELS
# ===============================
spring.email.host=smtp.gmail.com
spring.email.port=587
spring.email.senderEmail=gsgsystems100@gmail.com
spring.email.senderPassword=jtjlvwvhksvtyqgy
spring.email.host.url =http://localhost:8090/login_get

-Djavax.net.debug=all


spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp,starttls.enable=true

