server.port = 8080

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

rabbitmq.queue.name=supernet_queue
rabbitmq.exchange.name=supernet_exchange
rabbitmq.routingkey=supernet_rounting_key
rabbitmq.json_queue.name=supernet_json_queue
rabbitmq.json_routingkey=supernet_json_routing_key
rabbitmq.json_routingkey1=supernet_json_routing_key1