AppName = SuperSignAdminWeb.com	
EnableHTTP = true	
HTTPPort=5030	
EnableHTTPS=false	
ServerTimeOut=900	
RunMode = dev	
SessionProviderName=redis	
SessionProviderConfig=127.0.0.1:6379,100,,1	
RedisConnectionString=127.0.0.1:6379,100,,2	
cookieLifeTime=3600	
gclifetime=3600	
maxLifetime=900	
loglevel=Debug	
ChannelNAme=SwtichAdmin	
ChannelType=WEB	
ChannelIP=127.0.0.1	
ChannelIPType=Ipv4	
CopyRequestBody=true	
CountryTimeZone=Asia/Kolkata	
DateFormat=""	
TimeFormat=""	
DateLayout="2006-01-02"	
DBType=postgres	
DBIP=127.0.0.1	
DBPort=5432	
DBName=super_sign
DBUsername=postgres	
DBPassword=Manasa@246

EMAIL_NOTIFY_USERNAME=noreply@supernet-india.com
EMAIL_NOTIFY_PASSWORD=$noreply$@123
EMAIL_NOTIFY_URL=smtp.gmail.com
EMAIL_NOTIFY_TIMEOUT=587

#0 - no auth, 1 - auth, 2 - auth no tls
EMAIL_AUTH_CONFIG_MODE=1

EMAIL_TEMPLATE=./views/email/Registration.html

FORGOT_EMAIL_TEMPLATE=./views/email/Forgotpassword.html

VERIFY_EMAIL_TEMPLATE=./views/email/LoginUser.html

CUSTOMER_EMAIL_TEMPLATE=./views/email/CustomerRegistration.html

#VERFIY_EMAIL_TEMPLATE=http://139.59.81.65:5020/Email/UserRegistration

EMAIL_APPLICATION_LOGIN_URL=http://139.59.81.65:5030/


VALIDATION_LANG_PATH=/conf


LOGIN_COUNT=3

MAIN_PATH=/
LOGIN_PATH=/Login
LOGOUT_PATH=/Logout
DASHBOARD_PATH=/Dashboard

CHANGE_PASSWORD_PATH=/ChangePassword
FORGOT_PASSWORD_PATH=/ForgotPassword













































